# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Movie Title')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'verbose_name': 'Movie',
                'db_table': 'movie',
            },
        ),
    ]
